---
name: final-project
break: true
indent: 4
---
README.md:
    ConfirmFileExists
    MatchFileFragment --fragment "TODO" --count 0 --exact
    MatchFileFragment --fragment "{Your Name Here}" --count -0 --exact

src/main:
    java:
        finalproject/LabProject.java:
            ConfirmFileExists

src/starter:
    java:
        finalproject/LabProject.java:
            ConfirmFileExists
        

project:
    reflection.md:
        ConfirmFileExists
        CountMarkdownTags --tag "heading" --count 9
        MatchFileFragment --fragment "TODO" --count 0 --exact
        CountFileWords --count 750
            
writing:
    reflection.md:
        ConfirmFileExists
        CountMarkdownTags --tag "heading" --count 5
        CountMarkdownTags --tag "code_block" --count 1
            
ExecuteCommand --command "gradle build"
ExecuteCommand --command "gradle run"
